import SwiftUI

struct GuideSelectionView: View {
    @EnvironmentObject var guideCatalog: GuideCatalogStore
    @State private var previewPlayer: GuideAudioPlayer?
    @State private var previewingVoiceID: String?
    @State private var toastMessage: String?

    var body: some View {
        Form {
            Section(String(localized: "guide.persona.section.title", defaultValue: "Coach")) {
                ForEach(guideCatalog.templates) { template in
                    Button {
                        stopVoicePreview()
                        guideCatalog.setCoachPersona(id: template.id)
                    } label: {
                        HStack(spacing: 12) {
                            VStack(alignment: .leading, spacing: 3) {
                                Text(template.displayName)
                                    .foregroundStyle(.primary)
                                Text(template.tagline)
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                            Spacer()
                            if guideCatalog.selectedTemplate.id == template.id {
                                Image(systemName: "checkmark.circle.fill")
                                    .foregroundStyle(.orange)
                            }
                        }
                        .contentShape(Rectangle())
                    }
                    .buttonStyle(.plain)
                }
            }

            Section(String(localized: "guide.voice.section.title", defaultValue: "Voice")) {
                ForEach(guideCatalog.selectedTemplate.voiceOptions) { voice in
                    voiceButton(voice)
                }
                Text(String(localized: "guide.voice.server_audio.help", defaultValue: "Voice previews and coaching audio are generated by Plainstride’s configured AI service and cached for reliable playback."))
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }

            Section(String(localized: "guide.contract.section.title", defaultValue: "Coaching level")) {
                Picker(
                    String(localized: "guide.contract.picker.title", defaultValue: "Coaching level"),
                    selection: coachingContractBinding
                ) {
                    ForEach(CoachingContract.allCases) { contract in
                        Text(contract.displayName).tag(contract)
                    }
                }
                .pickerStyle(.segmented)

                Text(guideCatalog.selection.coachingContract.detail)
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }

            Section(String(localized: "guide.tone.section.title", defaultValue: "Coaching tone")) {
                Picker(
                    String(localized: "guide.tone.picker.title", defaultValue: "Coaching tone"),
                    selection: intensityBinding
                ) {
                    ForEach(GuidanceIntensity.allCases) { intensity in
                        Text(intensity.displayName).tag(intensity)
                    }
                }
                .pickerStyle(.segmented)
            }

            Section(String(localized: "guide.updates.section.title", defaultValue: "Stat updates")) {
                Picker(
                    String(localized: "guide.updates.picker.title", defaultValue: "Stat updates"),
                    selection: nudgeFrequencyBinding
                ) {
                    ForEach(NudgeFrequency.allCases) { frequency in
                        Text(frequency.displayName).tag(frequency)
                    }
                }
                .pickerStyle(.segmented)

                Text(String(localized: "guide.updates.help", defaultValue: "Controls regular time, distance, split pace, and average-pace announcements independently from coaching."))
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
        }
        .navigationTitle(String(localized: "live_guidance.title", defaultValue: "Live Guidance"))
        .task { await guideCatalog.refreshServerCatalog() }
        .overlay(alignment: .bottom) {
            if let toastMessage {
                Text(toastMessage)
                    .font(.footnote.weight(.semibold))
                    .foregroundStyle(.white)
                    .padding(.horizontal, 14)
                    .padding(.vertical, 10)
                    .background(.black.opacity(0.82), in: Capsule())
                    .padding(.bottom, 16)
                    .transition(.move(edge: .bottom).combined(with: .opacity))
            }
        }
        .onDisappear { stopVoicePreview() }
    }

    private func voiceButton(_ voice: GuideVoice) -> some View {
        HStack(spacing: 12) {
            Button { previewVoice(voice) } label: {
                Image(systemName: previewingVoiceID == voice.id ? "stop.circle.fill" : "play.circle.fill")
                    .font(.title2)
                    .foregroundStyle(.orange)
            }
            .buttonStyle(.plain)
            .accessibilityLabel(
                previewingVoiceID == voice.id
                    ? String(localized: "guide.preview.stop", defaultValue: "Stop Preview")
                    : String(localized: "guide.preview.voice", defaultValue: "Preview Voice")
            )
            .accessibilityHint(voice.displayName)

            Button {
                stopVoicePreview()
                guideCatalog.setVoice(id: voice.id)
            } label: {
                HStack(spacing: 12) {
                    VStack(alignment: .leading, spacing: 3) {
                        Text(voice.displayName)
                            .foregroundStyle(.primary)
                        Text(voice.description)
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                    Spacer()
                    if guideCatalog.selectedVoice.id == voice.id {
                        Image(systemName: "checkmark.circle.fill")
                            .foregroundStyle(.orange)
                    }
                }
                .contentShape(Rectangle())
            }
            .buttonStyle(.plain)
        }
    }

    private func previewVoice(_ voice: GuideVoice) {
        if previewingVoiceID == voice.id {
            stopVoicePreview()
            return
        }
        stopVoicePreview()
        guideCatalog.setVoice(id: voice.id)
        previewingVoiceID = voice.id
        Task { @MainActor in
            guard let data = await GuideAudioPackStore.shared.audioData(for: voice.previewAssetID) else {
                previewingVoiceID = nil
                showToast(String(localized: "guide.preview.unavailable", defaultValue: "Voice preview is unavailable right now."))
                return
            }
            let player = previewPlayer ?? GuideAudioPlayer()
            player.eventHandler = { event in
                if case .didFinish = event { previewingVoiceID = nil }
            }
            previewPlayer = player
            _ = player.play(data, interrupt: true)
        }
    }

    private func stopVoicePreview() {
        previewPlayer?.stopSpeaking(at: .immediate)
        previewingVoiceID = nil
    }

    private func showToast(_ message: String) {
        withAnimation { toastMessage = message }
        Task { @MainActor in
            try? await Task.sleep(for: .seconds(2.5))
            guard toastMessage == message else { return }
            withAnimation { toastMessage = nil }
        }
    }

    private var intensityBinding: Binding<GuidanceIntensity> {
        Binding(get: { guideCatalog.selection.intensity }, set: { guideCatalog.setIntensity($0) })
    }

    private var nudgeFrequencyBinding: Binding<NudgeFrequency> {
        Binding(get: { guideCatalog.selection.nudgeFrequency }, set: { guideCatalog.setNudgeFrequency($0) })
    }

    private var coachingContractBinding: Binding<CoachingContract> {
        Binding(get: { guideCatalog.selection.coachingContract }, set: { guideCatalog.setCoachingContract($0) })
    }
}
