package com.plainstride.outbound.feature.social

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.platform.LocalContext
import android.content.Intent
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import kotlinx.serialization.json.*
import com.plainstride.outbound.core.designsystem.*

@Composable fun SocialRoute(accountId: String, localeTag: String, targetType:String?=null,targetId:String?=null,onConditions:()->Unit={},onCommunity:()->Unit={},onNotifications:()->Unit={}, modifier: Modifier = Modifier, viewModel: SocialViewModel = hiltViewModel()) {
    var createCircle by rememberSaveable { mutableStateOf(false) };var inviteCircle by remember { mutableStateOf<CircleSummary?>(null) };var inviteEvent by remember { mutableStateOf<SocialEvent?>(null) }
    LaunchedEffect(accountId, localeTag) { viewModel.start(accountId, localeTag) }
    val state by viewModel.state.collectAsStateWithLifecycle()
    LaunchedEffect(targetType,targetId,state.loading){if(!state.loading&&targetType!=null&&targetId!=null)viewModel.openTarget(targetType,targetId)}
    SocialScreen(state, viewModel::refresh, viewModel::search, viewModel::openProfile, viewModel::openCircle, viewModel::openComments, viewModel::openTarget, onConditions, onCommunity, onNotifications, viewModel::toggleCheer, viewModel::joinGroup, viewModel::loadMore, viewModel::report, viewModel::block, {createCircle=true}, modifier)
    state.selectedProfile?.let { ProfileDialog(it, viewModel::closeProfile, { viewModel.connect(it) }, {it.connectionId?.let(viewModel::acceptConnection)}, {it.connectionId?.let(viewModel::removeConnection)}) }
    state.selectedCircle?.let { circle -> CircleDialog(circle, viewModel::closeCircle, { recipient, preset -> viewModel.cheerCircle(circle, recipient, preset) }, { viewModel.setCircleFocus(circle,"weekly_sessions",circle.target ?: 3,false) }, { viewModel.setCircleArchived(circle,circle.lifecycle!="archived") }, {inviteCircle=circle}) }
    state.selectedEvent?.let{event->SocialEventDialog(event,{viewModel.setEventRsvp(event,!event.joined);viewModel.closeTarget()},{inviteEvent=event},viewModel::closeTarget)}
    if(createCircle)PersonPickerDialog(stringResource(R.string.social_circle_create),state.home.connections,{createCircle=false}){person->viewModel.createCircle(null,listOf(person),java.util.TimeZone.getDefault().id);createCircle=false}
    inviteCircle?.let{circle->PersonPickerDialog(stringResource(R.string.social_invite),state.home.connections,{inviteCircle=null}){person->viewModel.inviteToCircle(circle,listOf(person),java.util.UUID.randomUUID().toString());inviteCircle=null}}
    inviteEvent?.let{event->PersonPickerDialog(stringResource(R.string.social_invite),state.home.connections,{inviteEvent=null}){person->viewModel.inviteToEvent(event,person);inviteEvent=null}}
    state.selectedGroup?.let{group->ActionDialog(group.name,stringResource(if(group.joined)R.string.social_leave else R.string.social_join),{viewModel.joinGroup(group);viewModel.closeTarget()},viewModel::closeTarget)}
    state.selectedInvitation?.let{invitation->AlertDialog(onDismissRequest=viewModel::closeTarget,title={Text(invitation.title)},confirmButton={TextButton({viewModel.respondToInvitation(invitation,true)}){Text(stringResource(R.string.social_accept))}},dismissButton={TextButton({viewModel.respondToInvitation(invitation,false)}){Text(stringResource(R.string.social_decline))}})}
    state.selectedPost?.let { CommentsDialog(it, state.comments, viewModel::addComment, viewModel::deleteComment, viewModel::closeComments) }
}
@Composable private fun ActionDialog(title:String,action:String,onAction:()->Unit,onClose:()->Unit)=AlertDialog(onDismissRequest=onClose,title={Text(title)},confirmButton={TextButton(onAction){Text(action)}},dismissButton={TextButton(onClose){Text(stringResource(R.string.social_done))}})

@Composable private fun SocialScreen(state: SocialUiState, refresh: () -> Unit, search: (String) -> Unit, openProfile: (SocialPerson) -> Unit, openCircle: (CircleSummary) -> Unit, comments: (SocialPost) -> Unit, openTarget:(String,String)->Unit, conditions:()->Unit, community:()->Unit, notifications:()->Unit, cheer: (SocialPost) -> Unit, group: (SocialGroup) -> Unit, loadMore: () -> Unit, report: (SocialPost, String) -> Unit, block: (SocialPost) -> Unit, createCircle:()->Unit, modifier: Modifier) {
    var safetyPost by remember { mutableStateOf<SocialPost?>(null) }
    val acceptedConnections = state.home.connections.filter { it.relationship in setOf("accepted", "connected") }.sortedWith(compareByDescending<SocialPerson> { it.isActive }.thenBy { it.displayName.substringBefore(' ').lowercase() })
    val incomingRequests = state.home.connections.filter { it.relationship == "pending" && it.connectionDirection == "incoming" }
    val circleInvitations = state.home.invitations.filter { it.kind == "circle" }
    LazyColumn(modifier.fillMaxSize(), contentPadding = PaddingValues(16.dp), verticalArrangement = Arrangement.spacedBy(14.dp)) {
        item { Row(verticalAlignment = Alignment.CenterVertically) { Text(stringResource(R.string.social_title), style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Bold, modifier = Modifier.weight(1f)); AssistChip(conditions,{Text(stringResource(R.string.social_conditions))},leadingIcon={Icon(Icons.Outlined.WbSunny,null)});IconButton(community) { Icon(Icons.Outlined.People, stringResource(R.string.social_community)) }; IconButton(notifications) { BadgedBox({ if (state.home.invitations.isNotEmpty()) Badge() }) { Icon(Icons.Outlined.Notifications, stringResource(R.string.social_notifications)) } } } }
        if (state.offline) item { AssistChip({}, { Text(stringResource(R.string.social_offline)) }, leadingIcon = { Icon(Icons.Outlined.CloudOff, null) }) }
        item { OutlinedTextField(state.search, search, modifier = Modifier.fillMaxWidth(), singleLine = true, label = { Text(stringResource(R.string.social_search_people)) }, leadingIcon = { Icon(Icons.Outlined.Search, null) }) }
        if (state.searchResults.isNotEmpty()) item { ElevatedCard { state.searchResults.forEach { PersonRow(it) { openProfile(it) } } } }
        if (incomingRequests.isNotEmpty()) item { ElevatedCard({ openProfile(incomingRequests.first()) }, Modifier.fillMaxWidth()) { Row(Modifier.padding(16.dp), verticalAlignment = Alignment.CenterVertically) { Icon(Icons.Outlined.PersonAdd, null); Spacer(Modifier.width(12.dp)); Text(stringResource(R.string.social_incoming_requests, incomingRequests.size), Modifier.weight(1f)); Icon(Icons.Outlined.ChevronRight, null) } } }
        item { SectionTitle(stringResource(R.string.social_connections)) }
        item { when { state.loading -> OutlinedCard(Modifier.fillMaxWidth().height(72.dp)) { LinearProgressIndicator(Modifier.fillMaxWidth()) }; acceptedConnections.isEmpty() -> EmptyCard(stringResource(R.string.social_connections_empty)); else -> LazyRow(horizontalArrangement = Arrangement.spacedBy(12.dp)) { items(acceptedConnections, key = SocialPerson::id) { PersonChip(it) { openProfile(it) } } } } }
        item { Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.weight(1f)){SectionTitle(stringResource(R.string.social_circle))};TextButton(createCircle){Icon(Icons.Outlined.Add,null);Text(stringResource(R.string.social_circle_create))}} }
        items(circleInvitations, key = SocialInvitation::id) { InvitationCard(it) { invitation -> openTarget("invitation", invitation.id) } }
        if (state.home.circles.isNotEmpty()) items(state.home.circles, key = CircleSummary::id) { circle -> OutlinedCard({ openCircle(circle) }, Modifier.fillMaxWidth()) { Row(Modifier.padding(16.dp)) { Text(circle.name, Modifier.weight(1f), fontWeight = FontWeight.SemiBold); circle.target?.let { Text("${circle.completed}/$it") } } } }
        else if (!state.loading && acceptedConnections.isNotEmpty()) item { EmptyCard(stringResource(R.string.social_circle_empty)) }
        if (state.home.recognitions.isNotEmpty()) item { ElevatedCard(Modifier.fillMaxWidth()) { Row(Modifier.padding(16.dp), verticalAlignment = Alignment.CenterVertically) { Icon(Icons.Outlined.AutoAwesome, null); Spacer(Modifier.width(12.dp)); Column { Text(stringResource(R.string.social_guide_noticed), fontWeight = FontWeight.SemiBold); Text(stringResource(R.string.social_recognition_earned)) } } } }
        item { SectionTitle(stringResource(R.string.social_upcoming)) }
        items(state.home.upcomingRuns, key = SocialEvent::id) { event -> EventCard(event) { openTarget("event",event.id) } }
        if (state.home.upcomingRuns.isEmpty()) item { EmptyCard(stringResource(R.string.social_upcoming_empty)) }
        item { SectionTitle(stringResource(R.string.social_past_activities)) }
        items(state.home.pastEvents, key = SocialEvent::id) { event -> EventCard(event) { openTarget("event",event.id) } }
        if (state.home.pastEvents.isEmpty()) item { EmptyCard(stringResource(R.string.social_past_empty)) }
        item { SectionTitle(stringResource(R.string.social_groups)) }
        items(state.home.groups, key = SocialGroup::id) { GroupCard(it) { group(it) } }
        item { SectionTitle(stringResource(R.string.social_feed)) }
        items(state.home.posts, key = SocialPost::id) { post -> PostCard(post, { openProfile(post.author) }, { cheer(post) }, { comments(post) }, { safetyPost = post }) }
        if (!state.loading && state.home.posts.isEmpty()) item { EmptyCard(stringResource(R.string.social_feed_empty)) }
        if (state.loading) item { Box(Modifier.fillMaxWidth().padding(24.dp), contentAlignment = Alignment.Center) { CircularProgressIndicator() } }
        if (state.home.nextCursor != null) item { Button(loadMore, Modifier.fillMaxWidth(), enabled = !state.feedLoading) { Text(stringResource(R.string.social_load_more)) } }
    }
    safetyPost?.let { post -> var reason by remember { mutableStateOf(ReportReason.OTHER) }; AlertDialog(onDismissRequest = { safetyPost = null }, title = { Text(stringResource(R.string.social_safety_title)) }, text = { Column { Text(stringResource(R.string.social_safety_body)); ReportReason.entries.forEach { option -> Row(verticalAlignment=Alignment.CenterVertically){RadioButton(reason==option,{reason=option});Text(reportReasonLabel(option))} } } }, confirmButton = { TextButton({ report(post, reason.wireValue); safetyPost = null }) { Text(stringResource(R.string.social_report)) } }, dismissButton = { TextButton({ block(post); safetyPost = null }) { Text(stringResource(R.string.social_block)) } }) }
}

@Composable private fun SectionTitle(text: String) = Text(text, style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.SemiBold)
@Composable private fun EmptyCard(text: String) = OutlinedCard(Modifier.fillMaxWidth()) { Text(text, Modifier.padding(18.dp), style = MaterialTheme.typography.bodyMedium) }
@Composable private fun PersonChip(person: SocialPerson, click: () -> Unit) = AssistChip(click, { Text(person.displayName.substringBefore(' ')) }, leadingIcon = { SocialAvatar(person, 30.dp) })
@Composable private fun PersonRow(person: SocialPerson, click: () -> Unit) = TextButton(click, Modifier.fillMaxWidth()) { SocialAvatar(person); Spacer(Modifier.width(12.dp)); Column(Modifier.weight(1f), horizontalAlignment = Alignment.Start) { Text(person.displayName); person.username?.let { Text("@$it", style = MaterialTheme.typography.bodySmall) } } }
@Composable private fun InvitationCard(invitation: SocialInvitation, review:(SocialInvitation)->Unit) = ElevatedCard(Modifier.fillMaxWidth()) { Column(Modifier.padding(16.dp)) { Text(invitation.title, fontWeight = FontWeight.SemiBold); Text(stringResource(R.string.social_invited_by, invitation.sender.displayName), style = MaterialTheme.typography.bodySmall); Button({review(invitation)}, Modifier.padding(top = 8.dp)) { Text(stringResource(R.string.social_review)) } } }
@Composable private fun EventCard(event: SocialEvent, open:()->Unit) = OutlinedCard(open,Modifier.fillMaxWidth()) { Column(Modifier.padding(16.dp)) { Text(event.name, fontWeight = FontWeight.SemiBold); Text(stringResource(R.string.social_hybrid)); event.locationName?.let { Text(it, style = MaterialTheme.typography.bodySmall) } } }
@Composable private fun GroupCard(group: SocialGroup, membership: () -> Unit) = OutlinedCard(Modifier.fillMaxWidth()) { Row(Modifier.padding(16.dp), verticalAlignment = Alignment.CenterVertically) { Column(Modifier.weight(1f)) { Text(group.name, fontWeight = FontWeight.SemiBold); Text(stringResource(R.string.social_members, group.memberCount), style = MaterialTheme.typography.bodySmall) }; TextButton(membership) { Text(stringResource(if (group.joined) R.string.social_leave else R.string.social_join)) } } }
@Composable private fun PostCard(post: SocialPost, profile: () -> Unit, cheer: () -> Unit, comments:()->Unit, safety: () -> Unit) = ElevatedCard(Modifier.fillMaxWidth()) { val cheerLabel=stringResource(if(post.viewerHasCheered)R.string.social_remove_cheer else R.string.social_add_cheer);Column { Row(Modifier.fillMaxWidth().padding(12.dp), verticalAlignment = Alignment.CenterVertically) { TextButton(profile, Modifier.weight(1f)) { SocialAvatar(post.author,36.dp); Spacer(Modifier.width(10.dp)); Column(horizontalAlignment=Alignment.Start){Text(post.author.displayName,fontWeight=FontWeight.SemiBold);post.activity?.startedAt?.let{Text(formatSocialDate(it),style=MaterialTheme.typography.bodySmall)}} }; IconButton(safety) { Icon(Icons.Outlined.MoreVert, stringResource(R.string.social_more)) } }; Box { post.activity?.route.routeCoordinates().takeIf { it.size > 1 }?.let { PlainstrideRouteMap(it, Modifier.fillMaxWidth().height(210.dp)) } ?: Surface(Modifier.fillMaxWidth().height(210.dp), color = MaterialTheme.colorScheme.surfaceVariant) { Box(contentAlignment = Alignment.Center) { Icon(Icons.Outlined.Route, stringResource(R.string.social_route), Modifier.size(44.dp)) } };post.activity?.let{activity->Surface(Modifier.align(Alignment.BottomCenter).fillMaxWidth(),color=MaterialTheme.colorScheme.scrim.copy(alpha=.72f)){Row(Modifier.padding(12.dp),horizontalArrangement=Arrangement.SpaceEvenly){ActivityStat(formatDistance(activity.distanceM),stringResource(R.string.social_distance));ActivityStat(formatDuration(activity.durationSecs),stringResource(R.string.social_time));ActivityStat(formatPace(activity.averagePaceSecsPerKm),stringResource(R.string.social_pace))}}} }; Column(Modifier.padding(16.dp)) { post.activity?.let { Text(it.title, fontWeight = FontWeight.SemiBold) }; post.caption?.let { Text(it, Modifier.padding(top = 6.dp)) }; Row(verticalAlignment = Alignment.CenterVertically) { IconButton(cheer, Modifier.sizeIn(minWidth=48.dp,minHeight=48.dp).semantics { contentDescription = cheerLabel }) { Icon(if (post.viewerHasCheered) Icons.Outlined.Favorite else Icons.Outlined.FavoriteBorder, null) }; Text(post.cheerCount.toString()); Spacer(Modifier.width(18.dp)); IconButton(comments,Modifier.sizeIn(minWidth=48.dp,minHeight=48.dp)){Icon(Icons.Outlined.ChatBubbleOutline,stringResource(R.string.social_comments))};Text(post.commentCount.toString()) } } } }

@Composable private fun ActivityStat(value:String,label:String)=Column(horizontalAlignment=Alignment.CenterHorizontally){Text(value,color=MaterialTheme.colorScheme.inverseOnSurface,fontWeight=FontWeight.Bold);Text(label,color=MaterialTheme.colorScheme.inverseOnSurface,style=MaterialTheme.typography.labelSmall)}
private fun formatDistance(value:Double?)=value?.let{"%.2f km".format(it/1000)} ?: "—"
private fun formatDuration(value:Int?)=value?.let{"%d:%02d".format(it/60,it%60)} ?: "—"
private fun formatPace(value:Double?)=value?.let{"%d:%02d /km".format(it.toInt()/60,it.toInt()%60)} ?: "—"
private fun formatSocialDate(value:String)=runCatching{java.time.OffsetDateTime.parse(value).format(java.time.format.DateTimeFormatter.ofLocalizedDateTime(java.time.format.FormatStyle.MEDIUM,java.time.format.FormatStyle.SHORT))}.getOrDefault("")

@Composable private fun CommentsDialog(post:SocialPost,comments:List<SocialComment>,add:(String)->Unit,delete:(SocialComment)->Unit,close:()->Unit){var body by rememberSaveable{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text(stringResource(R.string.social_comments_for,post.author.displayName))},text={Column{LazyColumn(Modifier.heightIn(max=320.dp)){items(comments,key=SocialComment::id){comment->Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(comment.author.displayName,fontWeight=FontWeight.SemiBold);Text(comment.body)};if(comment.canDelete)IconButton({delete(comment)}){Icon(Icons.Outlined.Delete,stringResource(R.string.social_delete_comment))}}}};OutlinedTextField(body,{body=it.take(500)},Modifier.fillMaxWidth(),label={Text(stringResource(R.string.social_add_comment))})}},confirmButton={TextButton({if(body.isNotBlank()){add(body);body=""}}){Text(stringResource(R.string.social_post_comment))}},dismissButton={TextButton(close){Text(stringResource(R.string.social_done))}})}

private fun JsonElement?.routeCoordinates(): List<MapCoordinate> {
    val root = this as? JsonObject ?: return emptyList()
    val raw = (root["coordinates"] ?: (root["geometry"] as? JsonObject)?.get("coordinates")) as? JsonArray ?: return emptyList()
    val line = if (raw.firstOrNull() is JsonPrimitive) listOf(raw) else raw.mapNotNull { it as? JsonArray }
    return line.mapNotNull { pair -> val lon=(pair.getOrNull(0) as? JsonPrimitive)?.doubleOrNull; val lat=(pair.getOrNull(1) as? JsonPrimitive)?.doubleOrNull; if(lat!=null&&lon!=null) MapCoordinate(lat,lon) else null }
}
@Composable private fun ProfileDialog(person:SocialPerson,close:()->Unit,connect:()->Unit,accept:()->Unit,remove:()->Unit){
 val context=LocalContext.current;val shareLabel=stringResource(R.string.social_share_award_text,person.displayName)
 AlertDialog(onDismissRequest=close,icon={Icon(Icons.Outlined.AccountCircle,null)},title={Text(person.displayName)},text={Column{person.username?.let{Text("@$it")};Text(stringResource(R.string.social_relationship,relationshipLabel(person.relationship)),Modifier.padding(top=8.dp));if(person.recognitions.isNotEmpty()){Text(stringResource(R.string.social_milestones,person.recognitions.size),Modifier.padding(top=12.dp));person.recognitions.filter{it.shareable}.forEach{award->val badge=badgeLabel(award.badgeId);TextButton({context.startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,"$shareLabel · $badge"),null))}){Icon(Icons.Outlined.Share,null);Spacer(Modifier.width(8.dp));Text(stringResource(R.string.social_share_award_named,badge))}}}}},confirmButton={Row{when{person.relationship=="none"->TextButton(connect){Text(stringResource(R.string.social_connect))};person.relationship=="pending"&&person.connectionDirection=="incoming"->TextButton(accept){Text(stringResource(R.string.social_accept))};else->TextButton(remove){Text(stringResource(R.string.social_remove_connection))}};TextButton(close){Text(stringResource(R.string.social_done))}}})
}
@Composable private fun reportReasonLabel(reason:ReportReason)=stringResource(when(reason){ReportReason.HARASSMENT->R.string.social_reason_harassment;ReportReason.HATE->R.string.social_reason_hate;ReportReason.SPAM->R.string.social_reason_spam;ReportReason.SEXUAL->R.string.social_reason_sexual;ReportReason.VIOLENCE->R.string.social_reason_violence;ReportReason.PRIVACY->R.string.social_reason_privacy;ReportReason.OTHER->R.string.social_reason_other})
@Composable private fun relationshipLabel(value:String)=when(value){"accepted","connected"->stringResource(R.string.social_relationship_connected);"pending"->stringResource(R.string.social_relationship_pending);else->stringResource(R.string.social_relationship_none)}
@Composable private fun badgeLabel(value:String)=stringResource(R.string.social_award_badge)
@Composable private fun CircleDialog(circle: CircleSummary, close: () -> Unit, cheer: (String, String) -> Unit,focus:()->Unit,archive:()->Unit,invite:()->Unit) = AlertDialog(onDismissRequest = close, title = { Text(circle.name) }, text = { LazyColumn { item { Text(stringResource(R.string.social_circle_progress, circle.completed, circle.target ?: 0)) }; items(circle.members, key = { it.person.id }) { member -> Row(Modifier.fillMaxWidth().padding(vertical = 8.dp), verticalAlignment = Alignment.CenterVertically) { Text(member.person.displayName, Modifier.weight(1f)); IconButton({ cheer(member.person.id, "encouragement") }) { Icon(Icons.Outlined.FavoriteBorder, stringResource(R.string.social_cheer)) } } };item{TextButton(invite){Text(stringResource(R.string.social_invite))};Row{TextButton(focus){Text(stringResource(R.string.social_circle_set_focus))};TextButton(archive){Text(stringResource(if(circle.lifecycle=="archived")R.string.social_circle_reactivate else R.string.social_circle_archive))}}} } }, confirmButton = { TextButton(close) { Text(stringResource(R.string.social_done)) } })
@Composable private fun SocialEventDialog(event:SocialEvent,rsvp:()->Unit,invite:()->Unit,close:()->Unit)=AlertDialog(onDismissRequest=close,title={Text(event.name)},confirmButton={Row{TextButton(rsvp){Text(stringResource(if(event.joined)R.string.social_leave else R.string.social_join))};TextButton(invite){Text(stringResource(R.string.social_invite))}}},dismissButton={TextButton(close){Text(stringResource(R.string.social_done))}})
@Composable private fun PersonPickerDialog(title:String,people:List<SocialPerson>,close:()->Unit,confirm:(SocialPerson)->Unit){var selected by remember{mutableStateOf<SocialPerson?>(null)};AlertDialog(onDismissRequest=close,title={Text(title)},text={if(people.isEmpty())Text(stringResource(R.string.social_connections_empty))else LazyColumn{items(people,key=SocialPerson::id){person->Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){RadioButton(selected?.id==person.id,{selected=person});Text(person.displayName)}}}},confirmButton={TextButton({selected?.let(confirm)},enabled=selected!=null){Text(stringResource(R.string.social_invite))}},dismissButton={TextButton(close){Text(stringResource(R.string.social_done))}})}
